### ISSUE TITLE
TypeError: params.then is not a function

### ISSUE THREAD

**Issue by aysong** [jvarness/hubot-lunchtime#17]
Saw that #14 also had this problem. But I installed the latest npm package for hubot-yelp so your fix should have worked. Tried removing the parens around "params" but that still says error. Any ideas?

`ERROR TypeError: params.then is not a function
  at queryYelp (/home/ec2-user/hiphubot/node_modules/hubot-yelp/src/lunchtime.coffee:41:3, <js>:27:31)
  at TextListener.callback (/home/ec2-user/hiphubot/node_modules/hubot-yelp/src/lunchtime.coffee:59:5, <js>:50:14)
  at executeListener (/home/ec2-user/hiphubot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/home/ec2-user/hiphubot/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /home/ec2-user/hiphubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/home/ec2-user/hiphubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/home/ec2-user/hiphubot/node_modules/async/lib/async.js:268:15)
  at /home/ec2-user/hiphubot/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by jvarness** [comment]
Did you restart your hubot after installing the latest? I know that hubot scripts won't pick up the latest unless the bot is turned off and on again.

**Comment by aysong** [comment]
Yeah, it's been on and off since yesterday when I installed hubot-yelp for the first time. Tried toying with it to see if I could fix it but nothing yet.

**Comment by jvarness** [comment]
What JS does coffeescript compile the script to? It appears to be correct when I past it into the coffeescript website.

Have you tried upgrading your version of coffeescript?

**Comment by aysong** [comment]
Oops, looks like updating coffeescript fixed it. My b
Although I'm still not getting any messages printed out, that is a separate issue that I will try to troubleshoot before I create a new issue here. Thanks!

**Comment by jvarness** [comment]
@aysong please make sure your API tokens are registered with Yelp's new API (Fusion).

Yelp's V2 API will be deprecated soon: https://engineeringblog.yelp.com/2017/06/upcoming-deprecation-of-yelp-api-v2.html
